from pathlib import Path
import re

root=Path('en')
files=list(root.glob('*.html'))
for p in files:
    h=p.read_text(encoding='utf-8')
    h=h.replace('Old townApartments','AltstadtApartments').replace('Old townApartment','AltstadtApartment')
    h=h.replace('in der Old town','in the old town').replace('mitten in der Old town','in the heart of the old town')
    h=h.replace('Ferienwohnungen','Holiday apartments').replace('Ferienwohnung','Holiday apartment')
    h=h.replace('Eigene Küche','Private kitchen').replace('kostenloses WLAN','free Wi-Fi').replace('kostenloses WLAN','free Wi-Fi')
    h=h.replace('für bis zu','for up to').replace('beziehungsweise','or').replace('jeweils eine voll ausgestattete Küche','a fully equipped kitchen in each apartment')
    h=h.replace('inLanguage\": \"de\"','inLanguage\": \"en\"').replace('"inLanguage":"de"','"inLanguage":"en"')
    h=h.replace('Das DesignApartment · bis zu 6 guests','DesignApartment · up to 6 guests')
    h=h.replace('Helles Wohnzimmer des DesignApartments mit Sofa und Kunst an der Wand','Bright living room in the DesignApartment with sofa and wall art')
    h=h.replace('Abendstimmung im AltstadtApartment mit Sofa und Parkettboden','Evening atmosphere in the AltstadtApartment with sofa and parquet flooring')
    h=h.replace('Wohnzimmer des AltstadtApartments mit Sofa, Fernseher und Holzboden','Living room of the AltstadtApartment with sofa, TV and wooden floor')
    h=h.replace('Küche des AltstadtApartments','Kitchen in the AltstadtApartment').replace('Badezimmer des AltstadtApartments','Bathroom in the AltstadtApartment')
    h=h.replace('Helles Wohnzimmer des DesignApartments','Bright living room in the DesignApartment').replace('Küche des DesignApartments','Kitchen in the DesignApartment').replace('Schlafzimmer des DesignApartments','Bedroom in the DesignApartment')
    h=h.replace('Hauptnavigation','Main navigation').replace('Mobile Navigation','Mobile navigation')
    h=h.replace('Menü öffnen','Open menu').replace('Menü schließen','Close menu')
    h=h.replace('Nach oben','Back to top')
    h=h.replace('Ferienwohnungen in Dinkelsbühl Old town | AltstadtApartments','Holiday apartments in Dinkelsbühl old town | AltstadtApartments')
    h=h.replace('AltstadtApartment in Dinkelsbühls Old town','AltstadtApartment in Dinkelsbühl old town')
    h=h.replace('DesignApartment in Dinkelsbühls Old town','DesignApartment in Dinkelsbühl old town')
    h=h.replace('Zwei Holiday apartments mitten in the old town von Dinkelsbühl: for up to 4 oder 6 guests. Private kitchen, free Wi-Fi und kurze Wege. Plan your stay.','Two holiday apartments in the heart of Dinkelsbühl old town for up to 4 or 6 guests. Private kitchen, free Wi-Fi and everything within easy walking distance. Plan your stay.')
    h=h.replace('Zwei Holiday apartments in the historischen Old town von Dinkelsbühl for up to 4 or 6 guests.','Two holiday apartments in the historic old town of Dinkelsbühl for up to 4 or 6 guests.')
    h=h.replace('Fully equipped kitchen in jeder Holiday apartment','Fully equipped kitchen in each apartment')
    h=h.replace('Wie viele guests können in den Apartments übernachten?','How many guests can stay in the apartments?')
    h=h.replace('Das AltstadtApartment bietet Platz for up to 4 guests. Im DesignApartment können for up to 6 guests übernachten. Die Wohnungen werden einzeln gebucht.','The AltstadtApartment sleeps up to 4 guests. The DesignApartment sleeps up to 6 guests. The apartments are booked separately.')
    h=h.replace('Gibt es WLAN und eine eigene Küche?','Is Wi-Fi and a private kitchen available?')
    h=h.replace('Ja. Beide Holiday apartments verfügen über free Wi-Fi und a fully equipped kitchen in each apartment.','Yes. Both apartments include free Wi-Fi and a fully equipped kitchen.')
    h=h.replace('Wo kann ich parken?','Where can I park?')
    h=h.replace('Kostenlose Parkplätze sind laut Gastgeber in etwa 5 Gehminuten erreichbar. Bitte fragen Sie vor der Anreise nach dem passenden Parkplatz und der Anfahrtsbeschreibung.','According to the host, free parking is available around a five-minute walk away. Please ask before arrival for parking and access details.')
    h=h.replace('Wann sind Anreise und Abreise möglich?','What are the check-in and check-out times?')
    h=h.replace('Laut den Booking terms ist die Anreise zwischen 15:00 und 18:00 Uhr und die Abreise bis 10:00 Uhr vorgesehen, sofern nichts anderes vereinbart wurde.','Check-in is generally between 3:00 pm and 6:00 pm, and check-out is by 10:00 am unless otherwise agreed.')
    h=h.replace('Sind Haustiere erlaubt?','Are pets allowed?')
    h=h.replace('Haustiere sind nur nach ausdrücklicher Vereinbarung mit dem Gastgeber erlaubt. Bitte klären Sie dies vor der Buchung. In den Unterkünften darf nicht geraucht werden.','Pets are only allowed by prior agreement with the host. Please clarify this before booking. Smoking is not permitted in the apartments.')
    h=h.replace('Wo sehe ich freie Termine und Preise?','Where can I see available dates and prices?')
    h=h.replace('Über „Plan your stay“ gelangen Sie zur Auswahl der Apartments und zur bestehenden Smoobu-Buchung. Dort prüfen Sie die verfügbaren Termine und die für Ihren Aufenthalt geltenden Konditionen.','Use “Plan your stay” to choose an apartment and open the existing Smoobu booking system, where you can check availability and the conditions for your stay.')
    # fix hreflang block explicitly
    de='https://altstadtapartments-dinkelsbuehl.de/' if p.name=='index.html' else f'https://altstadtapartments-dinkelsbuehl.de/{p.name}'
    en='https://altstadtapartments-dinkelsbuehl.de/en/' if p.name=='index.html' else f'https://altstadtapartments-dinkelsbuehl.de/en/{p.name}'
    h=re.sub(r'<link rel="alternate" hreflang="[^"]+" href="[^"]+"><link rel="alternate" hreflang="en" href="[^"]+"><link rel="alternate" hreflang="x-default" href="[^"]+">',f'<link rel="alternate" hreflang="de" href="{de}"><link rel="alternate" hreflang="en" href="{en}"><link rel="alternate" hreflang="x-default" href="{de}">',h,1)
    p.write_text(h,encoding='utf-8')
